#include "NexusSandbox-App/Core/NexusSandboxAppSystems.h"

namespace NxSA
{
	NEXUS_OBJECT_IMPLEMENTATION(SystemA)
	NEXUS_OBJECT_IMPLEMENTATION(SystemB)
	NEXUS_OBJECT_IMPLEMENTATION(SystemC)
	NEXUS_OBJECT_IMPLEMENTATION(SystemD)
	NEXUS_OBJECT_IMPLEMENTATION(SystemE)
}
